name: Publish docker image to github

on:
    # release:
        # types: [published]
    workflow_dispatch:

env:
    REGISTRY: ghcr.io
    IMAGE_NAME: ${{ github.repository }}

jobs:
    build-and-push:
        runs-on: ubuntu-latest
        
        permissions:
            contents: read
            packages: write
            attestations: write
            id-token: write

        steps:
            - name: Checkout code
              uses: actions/checkout@v5
              with:
                sparse-checkout: |
                  Dockerfile
                  nginx.conf

            - name: Download latest release
              uses: robinraju/release-downloader@v1.12
              with:
                latest: true
                fileName: 'nominatim-ui-*.zip'
                out-file-path: 'nominatim-ui.zip'
                extract: true

            - name: Move dist
              run: mv nominatim-ui/dist ./dist
              
            - name: Log in
              uses: docker/login-action@v3.4.0
              with:
                registry: ${{ env.REGISTRY }}
                username: ${{ github.actor }}
                password: ${{ secrets.GITHUB_TOKEN }}

            - name: Setup QEMU
              uses: docker/setup-qemu-action@v3.6.0
              with:
                platforms: linux/amd64,linux/arm64

            - name: Setup Buildx
              uses: docker/setup-buildx-action@v3.11.1

            - name: Extract metadata
              id: meta
              uses: docker/metadata-action@v5
              with:
                images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

            - name: Build and push
              id: push
              uses: docker/build-push-action@v6.18.0
              with:
                context: .
                push: true
                tags: ${{ steps.meta.outputs.tags }}
                labels: ${{ steps.meta.outputs.labels }}
                platforms: linux/amd64,linux/arm64

            - name: Create attestation
              uses: actions/attest-build-provenance@v2
              with:
                subject-name: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
                subject-digest: ${{ steps.push.outputs.digest }}
                push-to-registry: true
